export type TLocale = 'en' | 'de';
export type TTranslations = {
  howItWorks: string;
  gallery: string;
  prices: string;
  shipping: string;
  numberOfPeople: string;
  quantity: string;
  size: string;
  upload: string;
  shippingCart: string;
  personsAnimals: string;
  expressDeliveryIn: string;
  just7Days: string;
  expressDeliveryDays: string;
  handmade: string;
  satisfactionGuarantee: string;
  go_home: string;

  express_seven_days: string;
  express_expert_ratings: string;
  express_satisfaction: string;
  express_next: string;
  express_back: string;
  express_type: string;
  express_hi_featured: string;
  express_low_featured: string;
  express_type_of_photo: string;
  express_portrait: string;
  express_landscape: string;
  express_no_features: string;
  express_eyebrows: string;
  express_eyebrows_smile: string;

  main_hero_title: string;
  main_our_artists: string;
  main_design_now: string;
  main_express_shipping: string;
  main_just_7_days: string;
  main_how_davinci_works_title1: string;
  main_how_davinci_works_title2: string;
  main_create_a_portrait: string;
  main_hand_drawing: string;
  main_hight_quality_print: string;
  main_express_delivery: string;
  main_create_a_portrait_desc: string;
  main_hand_drawing_desc: string;
  main_hight_quality_print_desc: string;
  main_express_delivery_desc: string;
  main_gallery_title1: string;
  main_gallery_title2: string;
  main_our_artists_title1: string;
  main_our_artists_title2: string;
  main_talents_desc: string;
  main_talents_card_salutation: string;
  main_talents_card_desc: string;
  main_talents_card_name: string;
  main_talents_card_position: string;
  main_design_now_title1: string;
  main_design_now_title2: string;
  main_faq_title1: string;
  main_faq_title2: string;

  main_faq_question1: string;
  main_faq_answer1: string;
  main_faq_question2: string;
  main_faq_answer2: string;
  main_faq_question3: string;
  main_faq_answer3: string;
  main_faq_question4: string;
  main_faq_answer4: string;
  main_faq_question5: string;
  main_faq_answer5: string;

  size_choose_your_size: string;
};
